version: '3.4'

services:
  task3:
    image: task3
    build:
      context: task3/packages
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
